// Seed tool manifest for Plurics Tool Registry Phase 3 pilot.
// Each entry provides the tool name (used for idempotency checks) and the
// relative path from this file to the tool's tool.yaml.

export interface SeedToolDef {
  name: string;    // Must match the `name` field in the corresponding tool.yaml
  relPath: string; // Relative path from this file to tool.yaml
}

export const SEED_TOOLS: SeedToolDef[] = [
  { name: 'stats.mean',                relPath: './tools/stats.mean/tool.yaml' },
  { name: 'stats.fft',                 relPath: './tools/stats.fft/tool.yaml' },
  { name: 'json.load',                 relPath: './tools/json.load/tool.yaml' },
  { name: 'json.dump',                 relPath: './tools/json.dump/tool.yaml' },
  { name: 'pandas.load_csv',           relPath: './tools/pandas.load_csv/tool.yaml' },
  { name: 'pandas.save_csv',           relPath: './tools/pandas.save_csv/tool.yaml' },
  { name: 'stats.describe',            relPath: './tools/stats.describe/tool.yaml' },
  { name: 'stats.correlation_matrix',  relPath: './tools/stats.correlation_matrix/tool.yaml' },
  { name: 'sklearn.linear_regression', relPath: './tools/sklearn.linear_regression/tool.yaml' },
  { name: 'statsmodels.ols',           relPath: './tools/statsmodels.ols/tool.yaml' },
  { name: 'stats.median',            relPath: './tools/stats.median/tool.yaml' },
  { name: 'stats.variance',          relPath: './tools/stats.variance/tool.yaml' },
  { name: 'stats.quantile',          relPath: './tools/stats.quantile/tool.yaml' },
  { name: 'stats.histogram',         relPath: './tools/stats.histogram/tool.yaml' },
  { name: 'stats.autocorrelation',   relPath: './tools/stats.autocorrelation/tool.yaml' },
  { name: 'stats.cross_correlation', relPath: './tools/stats.cross_correlation/tool.yaml' },
  { name: 'pandas.load_parquet',     relPath: './tools/pandas.load_parquet/tool.yaml' },
  { name: 'pandas.save_parquet',     relPath: './tools/pandas.save_parquet/tool.yaml' },
  { name: 'yaml.load',               relPath: './tools/yaml.load/tool.yaml' },
  { name: 'yaml.dump',               relPath: './tools/yaml.dump/tool.yaml' },
  { name: 'stats.t_test',            relPath: './tools/stats.t_test/tool.yaml' },
  { name: 'stats.mann_whitney',      relPath: './tools/stats.mann_whitney/tool.yaml' },
  { name: 'stats.ks_test',          relPath: './tools/stats.ks_test/tool.yaml' },
  { name: 'stats.chi_square',       relPath: './tools/stats.chi_square/tool.yaml' },
  { name: 'stats.permutation_test', relPath: './tools/stats.permutation_test/tool.yaml' },
  { name: 'stats.bootstrap_ci',     relPath: './tools/stats.bootstrap_ci/tool.yaml' },
  { name: 'stats.adf_test',         relPath: './tools/stats.adf_test/tool.yaml' },
  { name: 'stats.ljung_box',        relPath: './tools/stats.ljung_box/tool.yaml' },
  { name: 'sklearn.logistic_regression', relPath: './tools/sklearn.logistic_regression/tool.yaml' },
  { name: 'sklearn.ridge_regression',    relPath: './tools/sklearn.ridge_regression/tool.yaml' },
  { name: 'sklearn.lasso',               relPath: './tools/sklearn.lasso/tool.yaml' },
  { name: 'statsmodels.glm',             relPath: './tools/statsmodels.glm/tool.yaml' },
  { name: 'sklearn.pca',  relPath: './tools/sklearn.pca/tool.yaml' },
  { name: 'sklearn.ica',  relPath: './tools/sklearn.ica/tool.yaml' },
  { name: 'sklearn.nmf',  relPath: './tools/sklearn.nmf/tool.yaml' },
  { name: 'sklearn.tsne', relPath: './tools/sklearn.tsne/tool.yaml' },
  { name: 'sklearn.umap', relPath: './tools/sklearn.umap/tool.yaml' },
  { name: 'sklearn.kmeans',            relPath: './tools/sklearn.kmeans/tool.yaml' },
  { name: 'sklearn.dbscan',            relPath: './tools/sklearn.dbscan/tool.yaml' },
  { name: 'sklearn.hierarchical',      relPath: './tools/sklearn.hierarchical/tool.yaml' },
  { name: 'sklearn.gaussian_mixture',  relPath: './tools/sklearn.gaussian_mixture/tool.yaml' },
  { name: 'statsmodels.arima',         relPath: './tools/statsmodels.arima/tool.yaml' },
  { name: 'statsmodels.garch',         relPath: './tools/statsmodels.garch/tool.yaml' },
  { name: 'statsmodels.decompose',     relPath: './tools/statsmodels.decompose/tool.yaml' },
  { name: 'statsmodels.seasonal_adjust', relPath: './tools/statsmodels.seasonal_adjust/tool.yaml' },
  { name: 'ts.granger_causality',          relPath: './tools/ts.granger_causality/tool.yaml' },
  { name: 'ta.compute_rsi',            relPath: './tools/ta.compute_rsi/tool.yaml' },
  { name: 'ta.compute_atr',            relPath: './tools/ta.compute_atr/tool.yaml' },
  { name: 'sympy.simplify',     relPath: './tools/sympy.simplify/tool.yaml' },
  { name: 'sympy.solve',        relPath: './tools/sympy.solve/tool.yaml' },
  { name: 'sympy.factor',       relPath: './tools/sympy.factor/tool.yaml' },
  { name: 'sympy.integrate',    relPath: './tools/sympy.integrate/tool.yaml' },
  { name: 'sympy.differentiate', relPath: './tools/sympy.differentiate/tool.yaml' },
  { name: 'sympy.limit',        relPath: './tools/sympy.limit/tool.yaml' },
  { name: 'pandas.filter_rows', relPath: './tools/pandas.filter_rows/tool.yaml' },
  { name: 'pandas.groupby_agg', relPath: './tools/pandas.groupby_agg/tool.yaml' },
  { name: 'pandas.pivot',       relPath: './tools/pandas.pivot/tool.yaml' },
  { name: 'pandas.resample',    relPath: './tools/pandas.resample/tool.yaml' },
  { name: 'pandas.merge',       relPath: './tools/pandas.merge/tool.yaml' },
  { name: 'pandas.rolling',     relPath: './tools/pandas.rolling/tool.yaml' },
  { name: 'numpy.reshape',      relPath: './tools/numpy.reshape/tool.yaml' },
  { name: 'numpy.normalize',    relPath: './tools/numpy.normalize/tool.yaml' },
  { name: 'scipy.minimize',     relPath: './tools/scipy.minimize/tool.yaml' },
  { name: 'scipy.curve_fit',    relPath: './tools/scipy.curve_fit/tool.yaml' },
  { name: 'scipy.root_finding', relPath: './tools/scipy.root_finding/tool.yaml' },
  { name: 'scipy.linprog',      relPath: './tools/scipy.linprog/tool.yaml' },
  { name: 'convert.DataFrame_to_NumpyArray', relPath: './tools/convert.DataFrame_to_NumpyArray/v1/tool.yaml' },
  { name: 'convert.NumpyArray_to_DataFrame', relPath: './tools/convert.NumpyArray_to_DataFrame/v1/tool.yaml' },
  { name: 'convert.OhlcFrame_to_ReturnSeries', relPath: './tools/convert.OhlcFrame_to_ReturnSeries/v1/tool.yaml' },
  // Wave 2 additions
  { name: 'sklearn.predict',              relPath: './tools/sklearn.predict/tool.yaml' },
  { name: 'sympy.parse',                  relPath: './tools/sympy.parse/tool.yaml' },
  { name: 'ts.compute_returns',           relPath: './tools/ts.compute_returns/tool.yaml' },
  // Wave 3 additions
  { name: 'plot.line',                    relPath: './tools/plot.line/tool.yaml' },
  { name: 'plot.histogram',               relPath: './tools/plot.histogram/tool.yaml' },
  { name: 'plot.scatter',                 relPath: './tools/plot.scatter/tool.yaml' },
  { name: 'plot.heatmap',                 relPath: './tools/plot.heatmap/tool.yaml' },
  { name: 'stats.bootstrap_distribution', relPath: './tools/stats.bootstrap_distribution/tool.yaml' },
  { name: 'stats.entropy',                relPath: './tools/stats.entropy/tool.yaml' },
  { name: 'stats.mutual_information',     relPath: './tools/stats.mutual_information/tool.yaml' },
  { name: 'sklearn.silhouette_score',     relPath: './tools/sklearn.silhouette_score/tool.yaml' },
];
